# fly.toml app configuration file generated for nll-modmail-dev on 2024-01-21T02:40:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nll-modmail"
primary_region = "ams"

[build]

[env]
  MODMAIL_HTTP_SERVER_ENABLED = "true"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
